version: "3.8"
services:
  vue:
    image: ghcr.io/stream-project/rmleditor:master
    environment:
      - VUE_APP_SERVICE_URL=${VUE_APP_SERVICE_URL}
    ports:
      - 80:8080

  service:
    image: ghcr.io/stream-project/rmleditor:master
    entrypoint: npm run service
    ports:
      - 3000:3000
