version: "3.8"
services:
  vue:
    image: ghcr.io/stream-project/rmleditor:master
    environment:
      - SERVICE_URL=http://service:3000/rmlmapper
    ports:
      - 80:80

  service:
    image: ghcr.io/stream-project/rmleditor:master
    entrypoint: npm run server
    ports:
      - 3000:3000
