version: "3.3"
services:
  vue:
    image: ghcr.io/stream-project/rmleditor:master
    environment:
      - VUE_APP_SERVICE_URL=${VUE_APP_SERVICE_URL}
    ports:
      - 8080:8080

  service:
    image: ghcr.io/stream-project/rmleditor:master
    entrypoint: npm run service
    ports:
      - 3000:3000
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
      DBA_PASSWORD: "DbaGraphPassword"
    volumes:
      - ./data/virtuoso:/testdata
    ports:
      - "8890:8890"
